### ISSUE TITLE
MacOS Command not found

### ISSUE THREAD

**Issue by pranavburnwal** [anned20/begoneads#5]
Initial installation was successful.
These file show up and then this.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/15976005/59269938-c62d3780-8c82-11e9-95a0-8d6115296435.png">

Using: Python 3.7.3

**Comment by anned20** [comment]
Did you run `python setup.py install`?

**Comment by pranavburnwal** [comment]
Yes. As the first line stated. That's running perfectly. No errors.

**Comment by haspre** [comment]
same on windows

**Comment by anned20** [comment]
Can you show me what `which begoneads` outputs? It might not be in your `$PATH` variable

**Comment by haspre** [comment]
thanks, that was helpful :)
I added the python script directory to the path (where the exe file begoneads.exe is located...)

that location can be found on windows using
`where /R \ begoneads*`

**Comment by pranavburnwal** [comment]
> Can you show me what `which begoneads` outputs? It might not be in your `$PATH` variable

It says begoneads not found. Can you instruct how I can manually execute it? I cannot find an executable.

**Comment by anned20** [comment]
I don't have a Mac to test on at this moment, but can you try [this](https://stackoverflow.com/questions/1935290/how-do-i-add-a-python-module-on-macos-x) @pranavburnwal?

**Comment by pranavburnwal** [comment]
Let me try this and report.

Thanks!

**Comment by pranavburnwal** [comment]
> I think by default /Library/Python/2.5/site-packages/ is part of your search path. This directory is usually used for third party libraries.

@anned20
The folder is empty in my case. And it points to 2.7 not (Python 3) Which I am using.

**Comment by marcyves** [comment]
@pranavburnwal if you are using Python 3, you should try to run `python3 setup.py install` instead.
That will perform the install in the correct library and put begoneads in your path

**Comment by pranavburnwal** [comment]
Yes, all this wile I have been using `python3` and `pip3` itself.

> python3 setup.py install

This was successful  fromteh very start. The first post is after running this.

**Comment by pranavburnwal** [comment]
Guys any help here?

**Comment by anned20** [comment]
You should be able to just use ```python begoneads/begoneads.py``` if you can't access it via your `$PATH` variable
