### ISSUE TITLE
Add instructions for people behind proxy

### ISSUE THREAD

**Issue by gilbert-fernandes** [anned20/begoneads#6]
For people being a proxy, perhaps add some instructions to be able to install it ?
I'm on Windows here so I started by defining the http and https proxy :

set http_proxy=http://user:pass@proxyIP:port
set https_proxy=https://user:pass@proxyIP:port

Then I've been able to install the program.

It's probably something everyone doing Python behind a Proxy knows but I had to search for it to make it work, so having it directly in the doc would have avoided me some Google search (and doing an easy_install pip for nothing)

**Comment by anned20** [comment]
I don't think this is specific to BeGoneAds and I don't know exactly where those steps would fit in. Can you make a pull request for it?

**Comment by gilbert-fernandes** [comment]
Sorry for delay. Will look into this tomorrow :)

**Comment by gilbert-fernandes** [comment]
Will do a pull request for this before the end of the week. Closing for now, it's on my TODO.
